name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Push to ECR
        uses: kciter/aws-ecr-action@v5
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: adamhjk/demodeploy
          region: us-west-2
          tags: latest,${{ github.sha }}
          extra_build_args: "--build-arg GIT_COMMIT=${{ github.sha }}"
          path: .
        env:
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Trigger System Initiative Deployment
        uses: systeminit/actions@v0.1
        with:
          changeSet: GHA-Deploy-${{ github.sha }}
          componentId: 01JQZ216QV907E3H95H8AXYPAH
          managementFunction: deployNewEcsTask
          domain: |
            Image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/adamhjk/demodeploy:${{ github.sha }}
          apiToken: ${{ secrets.SI_API_TOKEN }}
          waitForActions: true
